---
title: "ESR Cold Pool Index"
author: "Sean Rohan and Lewis Barnett"
date: "9/24/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(coldpool)
fig_res <- 300
proj_crs <- "EPSG:3338"

```

## Estimate cold pool area with candidate interpolation methods

```{r calc_index, message=FALSE, warning=FALSE, include=FALSE}

# Calculate cold pool area using candidate interpolation methods
cpa_df <- interpolate_gear_temp(temp_data_path = here::here("data", "2021-09-24_index_hauls_temperature_data.csv"),
                        proj_crs = proj_crs,
                        cell_resolution = 5000) # 5x5 km pixels
```

```{r plot_index}
cpindex_df <- coldpool:::cold_pool_index
cpi_sd <- sd(cpindex_df$COLD_POOL_AREA_KM2)
cpi_mean <- mean(cpindex_df$COLD_POOL_AREA_KM2)
cpindex_df <- cpindex_df %>%
  dplyr::mutate(dev = (COLD_POOL_AREA_KM2-cpi_mean)/cpi_sd)

ggplot(data = cpindex_df,
             aes(x = YEAR, 
                 y = COLD_POOL_AREA_KM2)) +
  geom_line() +
  geom_point(aes(fill = cut(dev, c(-3, -2, -1, 1, 2, 3))),
             shape = 21,
             size = rel(3)) +
  scale_fill_brewer(name = "Std. dev.", 
                    drop = FALSE, 
                    palette = "RdYlBu") +
  scale_x_continuous(name = "Year") +
  scale_y_continuous(name = expression('Cold Pool Area'~(km^2))) +
  theme_bw()
```